# Define which files to exclude from pre-commit checks
exclude: "node_modules|.git"

# Specify the default stages for the hooks to run
default_stages: [commit]
fail_fast: false

# Repository for general utility hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Specify the version of the hooks you want to use
    hooks:
      - id: trailing-whitespace
        files: "academia.*"
        exclude: ".*json$|.*txt$|.*csv|.*md"
      - id: check-yaml
      # - id: no-commit-to-branch
      #   args: ["--branch", "develop"]
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  # Repository for code formatting using Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss, css]
        exclude: |
          (?x)^(
              academia/public/dist/.*|
              .*node_modules.*|
              academia/public/js/controllers/.*|
              academia/templates/pages/.*|
              academia/templates/includes/.*
          )$
  #a Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        name: "Run ruff linter and apply fixes"
        # args: ["--fix"]
      - id: ruff-format
        name: "Format Python code"

# CI configuration
ci:
  autoupdate_schedule: weekly # Auto-update the hooks weekly
  skip: []
  submodules: false
